dev/diff:
	(cd ../../ && make install) && helmfile --helm-binary ~/.helm/plugins/helm-x/bin/helm-x --log-level debug diff

dev/apply:
	(cd ../../ && make install) && helmfile --helm-binary ~/.helm/plugins/helm-x/bin/helm-x --log-level debug apply
